keycloak:
  client: ${KC_CLIENT}
  realm: ${KC_REALM}
  server: ${KC_SERVER}
  principalClaimName: preferred_name
  ssl:
    disable-trust-manager: ${KC_DISABLE_TRUST_MANAGER:false}
  clients:
    auth:
      id: asiic-auth-client
      secret: ${KC_AUTH_SECRET}
    admin:
      id: asiic-admin-client
      secret: ${KC_ADMIN_SECRET}

spring:
  application:
    name: asiic-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server}/realms/${keycloak.realm}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3       # Tamaño fijo óptimo para 4 núcleos
      connection-timeout: 3000    # 3 segundos (falla rápido si se agotan)
      max-lifetime: 1200000       # 20 minutos (asegurarse de que la BD tenga wait_timeout > 25m)
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    from: ${MAIL_FROM}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true
server:
  port: 8888
