package com.assic.muni.domain.enums;

public enum IncidenciaEvent {
    // HAPPY PATH
    ENVIAR_INCIDENCIA,
    ASIGNAR_ANALISTA,
    ACEPTAR_INCIDENCIA,
    ASIGNAR_CAMPO,
    FINALIZAR_RECOLECCION,
    CONFIRMAR_INCIDENCIA,
    APERTURAR_CASO,
    INICIAR_CASO,
    CONFIRMAR_SOLUCION,
    FINALIZAR,
    RECHAZAR_INCIDENCIA,
    APELAR_INCIDENCIA,
    ASIGNAR_APELACION_ANALISTA,
    BLOQUEAR_CASO,
    RE_APERTURAR_CASO,
}
